package com.lenwotion.travel.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lenwotion.travel.bean.reminder.ArriveReminderBean;
import com.lenwotion.travel.bean.search.db.SearchBean;

import com.lenwotion.travel.greendao.ArriveReminderBeanDao;
import com.lenwotion.travel.greendao.SearchBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig arriveReminderBeanDaoConfig;
    private final DaoConfig searchBeanDaoConfig;

    private final ArriveReminderBeanDao arriveReminderBeanDao;
    private final SearchBeanDao searchBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        arriveReminderBeanDaoConfig = daoConfigMap.get(ArriveReminderBeanDao.class).clone();
        arriveReminderBeanDaoConfig.initIdentityScope(type);

        searchBeanDaoConfig = daoConfigMap.get(SearchBeanDao.class).clone();
        searchBeanDaoConfig.initIdentityScope(type);

        arriveReminderBeanDao = new ArriveReminderBeanDao(arriveReminderBeanDaoConfig, this);
        searchBeanDao = new SearchBeanDao(searchBeanDaoConfig, this);

        registerDao(ArriveReminderBean.class, arriveReminderBeanDao);
        registerDao(SearchBean.class, searchBeanDao);
    }
    
    public void clear() {
        arriveReminderBeanDaoConfig.clearIdentityScope();
        searchBeanDaoConfig.clearIdentityScope();
    }

    public ArriveReminderBeanDao getArriveReminderBeanDao() {
        return arriveReminderBeanDao;
    }

    public SearchBeanDao getSearchBeanDao() {
        return searchBeanDao;
    }

}
